### ISSUE TITLE
Orbit integration with Forem

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/community-management#4]

**Comment by viniblack** [comment]
I've started reading the orbit [documentation](https://orbit.love/docs/all/what-is-orbit)  to see all the integration possibilities it offers

**Comment by viniblack** [comment]
I read all the documentation and [found a promising topic about programs](https://orbit.love/docs/all/intro-to-programs), but it doesn't achieve our goal of having an easy way to get member data and update it in orbit.

In short, programs are organized structures for managing and nurturing communities in a more focused and intentional way. They can be thought of as spaces or groups within your community that have specific goals, such as promoting certain types of interactions, facilitating collaborative learning, coordinating events, or any other purpose you define.

**Comment by viniblack** [comment]
Reading the documentation I discovered that they have an API, I'm looking more closely but I found [promising endpoint](https://api.orbit.love/reference/post_workspace-slug-members)

**Comment by viniblack** [comment]
I'm setting up my local environment so that I can keep up with the demand
